kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: alkemio-collaborative-document-service-deployment
  labels:
    app: alkemio-collaborative-document-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkemio-collaborative-document-service
  template:
    metadata:
      labels:
        app: alkemio-collaborative-document-service
    spec:
      containers:
        - name: alkemio-collaborative-document-service
          image: alkemio.azurecr.io/alkemio-collaborative-document-service:latest
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: password
          envFrom:
            - secretRef:
                name: alkemio-secrets
            - configMapRef:
                name: alkemio-config
